export const CURRENCIES = [
  "USD",
  "EUR",
  "GBP",
  "NGN",
  "JPY",
  "CAD",
  "AUD",
  "CHF",
  "CNY",
  "INR",
  "ZAR",
  "AED",
  "BTC",
];

export const CURRENCY_INFO = {
  USD: {
    name: "US Dollar",
    symbol: "$",
    flag: "\u{1F1FA}\u{1F1F8}",
  },

  EUR: {
    name: "Euro",
    symbol: "\u20AC",
    flag: "\u{1F1EA}\u{1F1FA}",
  },

  GBP: {
    name: "British Pound",
    symbol: "\u00A3",
    flag: "\u{1F1EC}\u{1F1E7}",
  },

  NGN: {
    name: "Nigerian Naira",
    symbol: "\u20A6",
    flag: "\u{1F1F3}\u{1F1EC}",
  },

  JPY: {
    name: "Japanese Yen",
    symbol: "\u00A5",
    flag: "\u{1F1EF}\u{1F1F5}",
  },

  CAD: {
    name: "Canadian Dollar",
    symbol: "C$",
    flag: "\u{1F1E8}\u{1F1E6}",
  },

  AUD: {
    name: "Australian Dollar",
    symbol: "A$",
    flag: "\u{1F1E6}\u{1F1FA}",
  },

  CHF: {
    name: "Swiss Franc",
    symbol: "CHF",
    flag: "\u{1F1E8}\u{1F1ED}",
  },

  CNY: {
    name: "Chinese Yuan",
    symbol: "\u00A5",
    flag: "\u{1F1E8}\u{1F1F3}",
  },

  INR: {
    name: "Indian Rupee",
    symbol: "\u20B9",
    flag: "\u{1F1EE}\u{1F1F3}",
  },

  ZAR: {
    name: "South African Rand",
    symbol: "R",
    flag: "\u{1F1FF}\u{1F1E6}",
  },

  AED: {
    name: "UAE Dirham",
    symbol: "\u062F.\u0625",
    flag: "\u{1F1E6}\u{1F1EA}",
  },

  BTC: {
    name: "Bitcoin",
    symbol: "BTC",
    flag: "\u20BF",
  },
};

export const CURRENCY_COUNTRY_CODES = {
  AED: "AE", AFN: "AF", ALL: "AL", AMD: "AM", ANG: "CW", AOA: "AO", ARS: "AR", AUD: "AU",
  AWG: "AW", AZN: "AZ", BAM: "BA", BBD: "BB", BDT: "BD", BGN: "BG", BHD: "BH", BIF: "BI",
  BMD: "BM", BND: "BN", BOB: "BO", BRL: "BR", BSD: "BS", BTN: "BT", BWP: "BW", BYN: "BY",
  BZD: "BZ", CAD: "CA", CDF: "CD", CHF: "CH", CLF: "CL", CLP: "CL", CNH: "CN", CNY: "CN", COP: "CO", CRC: "CR",
  CUP: "CU", CVE: "CV", CZK: "CZ", DJF: "DJ", DKK: "DK", DOP: "DO", DZD: "DZ", EGP: "EG",
  ERN: "ER", ETB: "ET", EUR: "EU", FJD: "FJ", FKP: "FK", FOK: "FO", GBP: "GB", GEL: "GE",
  GGP: "GG", GHS: "GH", GIP: "GI", GMD: "GM", GNF: "GN", GTQ: "GT", GYD: "GY", HKD: "HK",
  HNL: "HN", HRK: "HR", HTG: "HT", HUF: "HU", IDR: "ID", ILS: "IL", IMP: "IM", INR: "IN",
  IQD: "IQ", IRR: "IR", ISK: "IS", JEP: "JE", JMD: "JM", JOD: "JO", JPY: "JP", KES: "KE",
  KGS: "KG", KHR: "KH", KID: "KI", KMF: "KM", KRW: "KR", KWD: "KW", KYD: "KY", KZT: "KZ",
  LAK: "LA", LBP: "LB", LKR: "LK", LRD: "LR", LSL: "LS", LYD: "LY", MAD: "MA", MDL: "MD",
  MGA: "MG", MKD: "MK", MMK: "MM", MNT: "MN", MOP: "MO", MRU: "MR", MUR: "MU", MVR: "MV",
  MWK: "MW", MXN: "MX", MYR: "MY", MZN: "MZ", NAD: "NA", NGN: "NG", NIO: "NI", NOK: "NO",
  NPR: "NP", NZD: "NZ", OMR: "OM", PAB: "PA", PEN: "PE", PGK: "PG", PHP: "PH", PKR: "PK",
  PLN: "PL", PYG: "PY", QAR: "QA", RON: "RO", RSD: "RS", RUB: "RU", RWF: "RW", SAR: "SA",
  SBD: "SB", SCR: "SC", SDG: "SD", SEK: "SE", SGD: "SG", SHP: "SH", SLE: "SL", SLL: "SL", SOS: "SO",
  SRD: "SR", SSP: "SS", STN: "ST", SYP: "SY", SZL: "SZ", THB: "TH", TJS: "TJ", TMT: "TM",
  TND: "TN", TOP: "TO", TRY: "TR", TTD: "TT", TVD: "TV", TWD: "TW", TZS: "TZ", UAH: "UA",
  UGX: "UG", USD: "US", UYU: "UY", UZS: "UZ", VES: "VE", VND: "VN", VUV: "VU", WST: "WS",
  XAF: "CM", XCD: "AG", XCG: "CW", XOF: "SN", XPF: "PF", YER: "YE", ZAR: "ZA", ZMW: "ZM",
  ZWG: "ZW", ZWL: "ZW",
};

export function countryCodeToFlag(countryCode) {
  if (!countryCode || countryCode.length !== 2) return "\u{1F310}";
  return [...countryCode.toUpperCase()]
    .map((char) => String.fromCodePoint(127397 + char.charCodeAt(0)))
    .join("");
}

export function getCurrencyFlag(code, info = CURRENCY_INFO[code] ?? {}) {
  return info.flag || countryCodeToFlag(CURRENCY_COUNTRY_CODES[code]);
}

export function getCurrencyInfo(code) {
  const info = CURRENCY_INFO[code] ?? {};
  return {
    name: info.name ?? code,
    symbol: info.symbol ?? code,
    flag: getCurrencyFlag(code, info),
  };
}

export const COUNTRIES = [
  { name: "Afghanistan", code: "AF", flag: "\u{1F1E6}\u{1F1EB}", dialCode: "+93" },
  { name: "Aland Islands", code: "AX", flag: "\u{1F1E6}\u{1F1FD}", dialCode: "+358" },
  { name: "Albania", code: "AL", flag: "\u{1F1E6}\u{1F1F1}", dialCode: "+355" },
  { name: "Algeria", code: "DZ", flag: "\u{1F1E9}\u{1F1FF}", dialCode: "+213" },
  { name: "American Samoa", code: "AS", flag: "\u{1F1E6}\u{1F1F8}", dialCode: "+1" },
  { name: "Andorra", code: "AD", flag: "\u{1F1E6}\u{1F1E9}", dialCode: "+376" },
  { name: "Angola", code: "AO", flag: "\u{1F1E6}\u{1F1F4}", dialCode: "+244" },
  { name: "Anguilla", code: "AI", flag: "\u{1F1E6}\u{1F1EE}", dialCode: "+1" },
  { name: "Antarctica", code: "AQ", flag: "\u{1F1E6}\u{1F1F6}", dialCode: "+672" },
  { name: "Antigua and Barbuda", code: "AG", flag: "\u{1F1E6}\u{1F1EC}", dialCode: "+1" },
  { name: "Argentina", code: "AR", flag: "\u{1F1E6}\u{1F1F7}", dialCode: "+54" },
  { name: "Armenia", code: "AM", flag: "\u{1F1E6}\u{1F1F2}", dialCode: "+374" },
  { name: "Aruba", code: "AW", flag: "\u{1F1E6}\u{1F1FC}", dialCode: "+297" },
  { name: "Australia", code: "AU", flag: "\u{1F1E6}\u{1F1FA}", dialCode: "+61" },
  { name: "Austria", code: "AT", flag: "\u{1F1E6}\u{1F1F9}", dialCode: "+43" },
  { name: "Azerbaijan", code: "AZ", flag: "\u{1F1E6}\u{1F1FF}", dialCode: "+994" },
  { name: "Bahrain", code: "BH", flag: "\u{1F1E7}\u{1F1ED}", dialCode: "+973" },
  { name: "Bangladesh", code: "BD", flag: "\u{1F1E7}\u{1F1E9}", dialCode: "+880" },
  { name: "Barbados", code: "BB", flag: "\u{1F1E7}\u{1F1E7}", dialCode: "+1" },
  { name: "Belarus", code: "BY", flag: "\u{1F1E7}\u{1F1FE}", dialCode: "+375" },
  { name: "Belgium", code: "BE", flag: "\u{1F1E7}\u{1F1EA}", dialCode: "+32" },
  { name: "Belize", code: "BZ", flag: "\u{1F1E7}\u{1F1FF}", dialCode: "+501" },
  { name: "Benin", code: "BJ", flag: "\u{1F1E7}\u{1F1EF}", dialCode: "+229" },
  { name: "Bermuda", code: "BM", flag: "\u{1F1E7}\u{1F1F2}", dialCode: "+1" },
  { name: "Bhutan", code: "BT", flag: "\u{1F1E7}\u{1F1F9}", dialCode: "+975" },
  { name: "Bolivia", code: "BO", flag: "\u{1F1E7}\u{1F1F4}", dialCode: "+591" },
  { name: "Bonaire, Sint Eustatius and Saba", code: "BQ", flag: "\u{1F1E7}\u{1F1F6}", dialCode: "+599" },
  { name: "Bosnia and Herzegovina", code: "BA", flag: "\u{1F1E7}\u{1F1E6}", dialCode: "+387" },
  { name: "Botswana", code: "BW", flag: "\u{1F1E7}\u{1F1FC}", dialCode: "+267" },
  { name: "Bouvet Island", code: "BV", flag: "\u{1F1E7}\u{1F1FB}", dialCode: "+47" },
  { name: "Brazil", code: "BR", flag: "\u{1F1E7}\u{1F1F7}", dialCode: "+55" },
  { name: "British Indian Ocean Territory", code: "IO", flag: "\u{1F1EE}\u{1F1F4}", dialCode: "+246" },
  { name: "Brunei", code: "BN", flag: "\u{1F1E7}\u{1F1F3}", dialCode: "+673" },
  { name: "Bulgaria", code: "BG", flag: "\u{1F1E7}\u{1F1EC}", dialCode: "+359" },
  { name: "Burkina Faso", code: "BF", flag: "\u{1F1E7}\u{1F1EB}", dialCode: "+226" },
  { name: "Burundi", code: "BI", flag: "\u{1F1E7}\u{1F1EE}", dialCode: "+257" },
  { name: "Cambodia", code: "KH", flag: "\u{1F1F0}\u{1F1ED}", dialCode: "+855" },
  { name: "Cameroon", code: "CM", flag: "\u{1F1E8}\u{1F1F2}", dialCode: "+237" },
  { name: "Canada", code: "CA", flag: "\u{1F1E8}\u{1F1E6}", dialCode: "+1" },
  { name: "Cape Verde", code: "CV", flag: "\u{1F1E8}\u{1F1FB}", dialCode: "+238" },
  { name: "Cayman Islands", code: "KY", flag: "\u{1F1F0}\u{1F1FE}", dialCode: "+1" },
  { name: "Central African Republic", code: "CF", flag: "\u{1F1E8}\u{1F1EB}", dialCode: "+236" },
  { name: "Chad", code: "TD", flag: "\u{1F1F9}\u{1F1E9}", dialCode: "+235" },
  { name: "Chile", code: "CL", flag: "\u{1F1E8}\u{1F1F1}", dialCode: "+56" },
  { name: "China", code: "CN", flag: "\u{1F1E8}\u{1F1F3}", dialCode: "+86" },
  { name: "Christmas Island", code: "CX", flag: "\u{1F1E8}\u{1F1FD}", dialCode: "+61" },
  { name: "Cocos (Keeling) Islands", code: "CC", flag: "\u{1F1E8}\u{1F1E8}", dialCode: "+61" },
  { name: "Colombia", code: "CO", flag: "\u{1F1E8}\u{1F1F4}", dialCode: "+57" },
  { name: "Comoros", code: "KM", flag: "\u{1F1F0}\u{1F1F2}", dialCode: "+269" },
  { name: "Congo", code: "CG", flag: "\u{1F1E8}\u{1F1EC}", dialCode: "+242" },
  { name: "Cook Islands", code: "CK", flag: "\u{1F1E8}\u{1F1F0}", dialCode: "+682" },
  { name: "Costa Rica", code: "CR", flag: "\u{1F1E8}\u{1F1F7}", dialCode: "+506" },
  { name: "Croatia", code: "HR", flag: "\u{1F1ED}\u{1F1F7}", dialCode: "+385" },
  { name: "Cuba", code: "CU", flag: "\u{1F1E8}\u{1F1FA}", dialCode: "+53" },
  { name: "Curacao", code: "CW", flag: "\u{1F1E8}\u{1F1FC}", dialCode: "+599" },
  { name: "Cyprus", code: "CY", flag: "\u{1F1E8}\u{1F1FE}", dialCode: "+357" },
  { name: "Czech Republic", code: "CZ", flag: "\u{1F1E8}\u{1F1FF}", dialCode: "+420" },
  { name: "Democratic Republic of the Congo", code: "CD", flag: "\u{1F1E8}\u{1F1E9}", dialCode: "+243" },
  { name: "Denmark", code: "DK", flag: "\u{1F1E9}\u{1F1F0}", dialCode: "+45" },
  { name: "Djibouti", code: "DJ", flag: "\u{1F1E9}\u{1F1EF}", dialCode: "+253" },
  { name: "Dominica", code: "DM", flag: "\u{1F1E9}\u{1F1F2}", dialCode: "+1" },
  { name: "Dominican Republic", code: "DO", flag: "\u{1F1E9}\u{1F1F4}", dialCode: "+1" },
  { name: "Ecuador", code: "EC", flag: "\u{1F1EA}\u{1F1E8}", dialCode: "+593" },
  { name: "Egypt", code: "EG", flag: "\u{1F1EA}\u{1F1EC}", dialCode: "+20" },
  { name: "El Salvador", code: "SV", flag: "\u{1F1F8}\u{1F1FB}", dialCode: "+503" },
  { name: "Equatorial Guinea", code: "GQ", flag: "\u{1F1EC}\u{1F1F6}", dialCode: "+240" },
  { name: "Eritrea", code: "ER", flag: "\u{1F1EA}\u{1F1F7}", dialCode: "+291" },
  { name: "Estonia", code: "EE", flag: "\u{1F1EA}\u{1F1EA}", dialCode: "+372" },
  { name: "Eswatini", code: "SZ", flag: "\u{1F1F8}\u{1F1FF}", dialCode: "+268" },
  { name: "Ethiopia", code: "ET", flag: "\u{1F1EA}\u{1F1F9}", dialCode: "+251" },
  { name: "Falkland Islands", code: "FK", flag: "\u{1F1EB}\u{1F1F0}", dialCode: "+500" },
  { name: "Faroe Islands", code: "FO", flag: "\u{1F1EB}\u{1F1F4}", dialCode: "+298" },
  { name: "Fiji Islands", code: "FJ", flag: "\u{1F1EB}\u{1F1EF}", dialCode: "+679" },
  { name: "Finland", code: "FI", flag: "\u{1F1EB}\u{1F1EE}", dialCode: "+358" },
  { name: "France", code: "FR", flag: "\u{1F1EB}\u{1F1F7}", dialCode: "+33" },
  { name: "French Guiana", code: "GF", flag: "\u{1F1EC}\u{1F1EB}", dialCode: "+594" },
  { name: "French Polynesia", code: "PF", flag: "\u{1F1F5}\u{1F1EB}", dialCode: "+689" },
  { name: "French Southern Territories", code: "TF", flag: "\u{1F1F9}\u{1F1EB}", dialCode: "+262" },
  { name: "Gabon", code: "GA", flag: "\u{1F1EC}\u{1F1E6}", dialCode: "+241" },
  { name: "Gambia", code: "GM", flag: "\u{1F1EC}\u{1F1F2}", dialCode: "+220" },
  { name: "Georgia", code: "GE", flag: "\u{1F1EC}\u{1F1EA}", dialCode: "+995" },
  { name: "Germany", code: "DE", flag: "\u{1F1E9}\u{1F1EA}", dialCode: "+49" },
  { name: "Ghana", code: "GH", flag: "\u{1F1EC}\u{1F1ED}", dialCode: "+233" },
  { name: "Gibraltar", code: "GI", flag: "\u{1F1EC}\u{1F1EE}", dialCode: "+350" },
  { name: "Greece", code: "GR", flag: "\u{1F1EC}\u{1F1F7}", dialCode: "+30" },
  { name: "Greenland", code: "GL", flag: "\u{1F1EC}\u{1F1F1}", dialCode: "+299" },
  { name: "Grenada", code: "GD", flag: "\u{1F1EC}\u{1F1E9}", dialCode: "+1" },
  { name: "Guadeloupe", code: "GP", flag: "\u{1F1EC}\u{1F1F5}", dialCode: "+590" },
  { name: "Guam", code: "GU", flag: "\u{1F1EC}\u{1F1FA}", dialCode: "+1" },
  { name: "Guatemala", code: "GT", flag: "\u{1F1EC}\u{1F1F9}", dialCode: "+502" },
  { name: "Guernsey", code: "GG", flag: "\u{1F1EC}\u{1F1EC}", dialCode: "+44" },
  { name: "Guinea", code: "GN", flag: "\u{1F1EC}\u{1F1F3}", dialCode: "+224" },
  { name: "Guinea-Bissau", code: "GW", flag: "\u{1F1EC}\u{1F1FC}", dialCode: "+245" },
  { name: "Guyana", code: "GY", flag: "\u{1F1EC}\u{1F1FE}", dialCode: "+592" },
  { name: "Haiti", code: "HT", flag: "\u{1F1ED}\u{1F1F9}", dialCode: "+509" },
  { name: "Heard Island and McDonald Islands", code: "HM", flag: "\u{1F1ED}\u{1F1F2}", dialCode: "+672" },
  { name: "Honduras", code: "HN", flag: "\u{1F1ED}\u{1F1F3}", dialCode: "+504" },
  { name: "Hong Kong", code: "HK", flag: "\u{1F1ED}\u{1F1F0}", dialCode: "+852" },
  { name: "Hungary", code: "HU", flag: "\u{1F1ED}\u{1F1FA}", dialCode: "+36" },
  { name: "Iceland", code: "IS", flag: "\u{1F1EE}\u{1F1F8}", dialCode: "+354" },
  { name: "India", code: "IN", flag: "\u{1F1EE}\u{1F1F3}", dialCode: "+91" },
  { name: "Indonesia", code: "ID", flag: "\u{1F1EE}\u{1F1E9}", dialCode: "+62" },
  { name: "Iran", code: "IR", flag: "\u{1F1EE}\u{1F1F7}", dialCode: "+98" },
  { name: "Iraq", code: "IQ", flag: "\u{1F1EE}\u{1F1F6}", dialCode: "+964" },
  { name: "Ireland", code: "IE", flag: "\u{1F1EE}\u{1F1EA}", dialCode: "+353" },
  { name: "Isle of Man", code: "IM", flag: "\u{1F1EE}\u{1F1F2}", dialCode: "+44" },
  { name: "Israel", code: "IL", flag: "\u{1F1EE}\u{1F1F1}", dialCode: "+972" },
  { name: "Italy", code: "IT", flag: "\u{1F1EE}\u{1F1F9}", dialCode: "+39" },
  { name: "Ivory Coast", code: "CI", flag: "\u{1F1E8}\u{1F1EE}", dialCode: "+225" },
  { name: "Jamaica", code: "JM", flag: "\u{1F1EF}\u{1F1F2}", dialCode: "+1" },
  { name: "Japan", code: "JP", flag: "\u{1F1EF}\u{1F1F5}", dialCode: "+81" },
  { name: "Jersey", code: "JE", flag: "\u{1F1EF}\u{1F1EA}", dialCode: "+44" },
  { name: "Jordan", code: "JO", flag: "\u{1F1EF}\u{1F1F4}", dialCode: "+962" },
  { name: "Kazakhstan", code: "KZ", flag: "\u{1F1F0}\u{1F1FF}", dialCode: "+7" },
  { name: "Kenya", code: "KE", flag: "\u{1F1F0}\u{1F1EA}", dialCode: "+254" },
  { name: "Kiribati", code: "KI", flag: "\u{1F1F0}\u{1F1EE}", dialCode: "+686" },
  { name: "Kosovo", code: "XK", flag: "\u{1F1FD}\u{1F1F0}", dialCode: "+383" },
  { name: "Kuwait", code: "KW", flag: "\u{1F1F0}\u{1F1FC}", dialCode: "+965" },
  { name: "Kyrgyzstan", code: "KG", flag: "\u{1F1F0}\u{1F1EC}", dialCode: "+996" },
  { name: "Laos", code: "LA", flag: "\u{1F1F1}\u{1F1E6}", dialCode: "+856" },
  { name: "Latvia", code: "LV", flag: "\u{1F1F1}\u{1F1FB}", dialCode: "+371" },
  { name: "Lebanon", code: "LB", flag: "\u{1F1F1}\u{1F1E7}", dialCode: "+961" },
  { name: "Lesotho", code: "LS", flag: "\u{1F1F1}\u{1F1F8}", dialCode: "+266" },
  { name: "Liberia", code: "LR", flag: "\u{1F1F1}\u{1F1F7}", dialCode: "+231" },
  { name: "Libya", code: "LY", flag: "\u{1F1F1}\u{1F1FE}", dialCode: "+218" },
  { name: "Liechtenstein", code: "LI", flag: "\u{1F1F1}\u{1F1EE}", dialCode: "+423" },
  { name: "Lithuania", code: "LT", flag: "\u{1F1F1}\u{1F1F9}", dialCode: "+370" },
  { name: "Luxembourg", code: "LU", flag: "\u{1F1F1}\u{1F1FA}", dialCode: "+352" },
  { name: "Macau", code: "MO", flag: "\u{1F1F2}\u{1F1F4}", dialCode: "+853" },
  { name: "Madagascar", code: "MG", flag: "\u{1F1F2}\u{1F1EC}", dialCode: "+261" },
  { name: "Malawi", code: "MW", flag: "\u{1F1F2}\u{1F1FC}", dialCode: "+265" },
  { name: "Malaysia", code: "MY", flag: "\u{1F1F2}\u{1F1FE}", dialCode: "+60" },
  { name: "Maldives", code: "MV", flag: "\u{1F1F2}\u{1F1FB}", dialCode: "+960" },
  { name: "Mali", code: "ML", flag: "\u{1F1F2}\u{1F1F1}", dialCode: "+223" },
  { name: "Malta", code: "MT", flag: "\u{1F1F2}\u{1F1F9}", dialCode: "+356" },
  { name: "Marshall Islands", code: "MH", flag: "\u{1F1F2}\u{1F1ED}", dialCode: "+692" },
  { name: "Martinique", code: "MQ", flag: "\u{1F1F2}\u{1F1F6}", dialCode: "+596" },
  { name: "Mauritania", code: "MR", flag: "\u{1F1F2}\u{1F1F7}", dialCode: "+222" },
  { name: "Mauritius", code: "MU", flag: "\u{1F1F2}\u{1F1FA}", dialCode: "+230" },
  { name: "Mayotte", code: "YT", flag: "\u{1F1FE}\u{1F1F9}", dialCode: "+262" },
  { name: "Mexico", code: "MX", flag: "\u{1F1F2}\u{1F1FD}", dialCode: "+52" },
  { name: "Micronesia", code: "FM", flag: "\u{1F1EB}\u{1F1F2}", dialCode: "+691" },
  { name: "Moldova", code: "MD", flag: "\u{1F1F2}\u{1F1E9}", dialCode: "+373" },
  { name: "Monaco", code: "MC", flag: "\u{1F1F2}\u{1F1E8}", dialCode: "+377" },
  { name: "Mongolia", code: "MN", flag: "\u{1F1F2}\u{1F1F3}", dialCode: "+976" },
  { name: "Montenegro", code: "ME", flag: "\u{1F1F2}\u{1F1EA}", dialCode: "+382" },
  { name: "Montserrat", code: "MS", flag: "\u{1F1F2}\u{1F1F8}", dialCode: "+1" },
  { name: "Morocco", code: "MA", flag: "\u{1F1F2}\u{1F1E6}", dialCode: "+212" },
  { name: "Mozambique", code: "MZ", flag: "\u{1F1F2}\u{1F1FF}", dialCode: "+258" },
  { name: "Myanmar", code: "MM", flag: "\u{1F1F2}\u{1F1F2}", dialCode: "+95" },
  { name: "Namibia", code: "NA", flag: "\u{1F1F3}\u{1F1E6}", dialCode: "+264" },
  { name: "Nauru", code: "NR", flag: "\u{1F1F3}\u{1F1F7}", dialCode: "+674" },
  { name: "Nepal", code: "NP", flag: "\u{1F1F3}\u{1F1F5}", dialCode: "+977" },
  { name: "Netherlands", code: "NL", flag: "\u{1F1F3}\u{1F1F1}", dialCode: "+31" },
  { name: "New Caledonia", code: "NC", flag: "\u{1F1F3}\u{1F1E8}", dialCode: "+687" },
  { name: "New Zealand", code: "NZ", flag: "\u{1F1F3}\u{1F1FF}", dialCode: "+64" },
  { name: "Nicaragua", code: "NI", flag: "\u{1F1F3}\u{1F1EE}", dialCode: "+505" },
  { name: "Niger", code: "NE", flag: "\u{1F1F3}\u{1F1EA}", dialCode: "+227" },
  { name: "Nigeria", code: "NG", flag: "\u{1F1F3}\u{1F1EC}", dialCode: "+234" },
  { name: "Niue", code: "NU", flag: "\u{1F1F3}\u{1F1FA}", dialCode: "+683" },
  { name: "Norfolk Island", code: "NF", flag: "\u{1F1F3}\u{1F1EB}", dialCode: "+672" },
  { name: "North Korea", code: "KP", flag: "\u{1F1F0}\u{1F1F5}", dialCode: "+850" },
  { name: "North Macedonia", code: "MK", flag: "\u{1F1F2}\u{1F1F0}", dialCode: "+389" },
  { name: "Northern Mariana Islands", code: "MP", flag: "\u{1F1F2}\u{1F1F5}", dialCode: "+1" },
  { name: "Norway", code: "NO", flag: "\u{1F1F3}\u{1F1F4}", dialCode: "+47" },
  { name: "Oman", code: "OM", flag: "\u{1F1F4}\u{1F1F2}", dialCode: "+968" },
  { name: "Pakistan", code: "PK", flag: "\u{1F1F5}\u{1F1F0}", dialCode: "+92" },
  { name: "Palau", code: "PW", flag: "\u{1F1F5}\u{1F1FC}", dialCode: "+680" },
  { name: "Palestinian Territory", code: "PS", flag: "\u{1F1F5}\u{1F1F8}", dialCode: "+970" },
  { name: "Panama", code: "PA", flag: "\u{1F1F5}\u{1F1E6}", dialCode: "+507" },
  { name: "Papua New Guinea", code: "PG", flag: "\u{1F1F5}\u{1F1EC}", dialCode: "+675" },
  { name: "Paraguay", code: "PY", flag: "\u{1F1F5}\u{1F1FE}", dialCode: "+595" },
  { name: "Peru", code: "PE", flag: "\u{1F1F5}\u{1F1EA}", dialCode: "+51" },
  { name: "Philippines", code: "PH", flag: "\u{1F1F5}\u{1F1ED}", dialCode: "+63" },
  { name: "Pitcairn Island", code: "PN", flag: "\u{1F1F5}\u{1F1F3}", dialCode: "+870" },
  { name: "Poland", code: "PL", flag: "\u{1F1F5}\u{1F1F1}", dialCode: "+48" },
  { name: "Portugal", code: "PT", flag: "\u{1F1F5}\u{1F1F9}", dialCode: "+351" },
  { name: "Puerto Rico", code: "PR", flag: "\u{1F1F5}\u{1F1F7}", dialCode: "+1" },
  { name: "Qatar", code: "QA", flag: "\u{1F1F6}\u{1F1E6}", dialCode: "+974" },
  { name: "Reunion", code: "RE", flag: "\u{1F1F7}\u{1F1EA}", dialCode: "+262" },
  { name: "Romania", code: "RO", flag: "\u{1F1F7}\u{1F1F4}", dialCode: "+40" },
  { name: "Russia", code: "RU", flag: "\u{1F1F7}\u{1F1FA}", dialCode: "+7" },
  { name: "Rwanda", code: "RW", flag: "\u{1F1F7}\u{1F1FC}", dialCode: "+250" },
  { name: "Saint Helena", code: "SH", flag: "\u{1F1F8}\u{1F1ED}", dialCode: "+290" },
  { name: "Saint Kitts and Nevis", code: "KN", flag: "\u{1F1F0}\u{1F1F3}", dialCode: "+1" },
  { name: "Saint Lucia", code: "LC", flag: "\u{1F1F1}\u{1F1E8}", dialCode: "+1" },
  { name: "Saint Pierre and Miquelon", code: "PM", flag: "\u{1F1F5}\u{1F1F2}", dialCode: "+508" },
  { name: "Saint Vincent and the Grenadines", code: "VC", flag: "\u{1F1FB}\u{1F1E8}", dialCode: "+1" },
  { name: "Saint-Barthelemy", code: "BL", flag: "\u{1F1E7}\u{1F1F1}", dialCode: "+590" },
  { name: "Saint-Martin", code: "MF", flag: "\u{1F1F2}\u{1F1EB}", dialCode: "+590" },
  { name: "Samoa", code: "WS", flag: "\u{1F1FC}\u{1F1F8}", dialCode: "+685" },
  { name: "San Marino", code: "SM", flag: "\u{1F1F8}\u{1F1F2}", dialCode: "+378" },
  { name: "Sao Tome and Principe", code: "ST", flag: "\u{1F1F8}\u{1F1F9}", dialCode: "+239" },
  { name: "Saudi Arabia", code: "SA", flag: "\u{1F1F8}\u{1F1E6}", dialCode: "+966" },
  { name: "Senegal", code: "SN", flag: "\u{1F1F8}\u{1F1F3}", dialCode: "+221" },
  { name: "Serbia", code: "RS", flag: "\u{1F1F7}\u{1F1F8}", dialCode: "+381" },
  { name: "Seychelles", code: "SC", flag: "\u{1F1F8}\u{1F1E8}", dialCode: "+248" },
  { name: "Sierra Leone", code: "SL", flag: "\u{1F1F8}\u{1F1F1}", dialCode: "+232" },
  { name: "Singapore", code: "SG", flag: "\u{1F1F8}\u{1F1EC}", dialCode: "+65" },
  { name: "Sint Maarten", code: "SX", flag: "\u{1F1F8}\u{1F1FD}", dialCode: "+1721" },
  { name: "Slovakia", code: "SK", flag: "\u{1F1F8}\u{1F1F0}", dialCode: "+421" },
  { name: "Slovenia", code: "SI", flag: "\u{1F1F8}\u{1F1EE}", dialCode: "+386" },
  { name: "Solomon Islands", code: "SB", flag: "\u{1F1F8}\u{1F1E7}", dialCode: "+677" },
  { name: "Somalia", code: "SO", flag: "\u{1F1F8}\u{1F1F4}", dialCode: "+252" },
  { name: "South Africa", code: "ZA", flag: "\u{1F1FF}\u{1F1E6}", dialCode: "+27" },
  { name: "South Georgia", code: "GS", flag: "\u{1F1EC}\u{1F1F8}", dialCode: "+500" },
  { name: "South Korea", code: "KR", flag: "\u{1F1F0}\u{1F1F7}", dialCode: "+82" },
  { name: "South Sudan", code: "SS", flag: "\u{1F1F8}\u{1F1F8}", dialCode: "+211" },
  { name: "Spain", code: "ES", flag: "\u{1F1EA}\u{1F1F8}", dialCode: "+34" },
  { name: "Sri Lanka", code: "LK", flag: "\u{1F1F1}\u{1F1F0}", dialCode: "+94" },
  { name: "Sudan", code: "SD", flag: "\u{1F1F8}\u{1F1E9}", dialCode: "+249" },
  { name: "Suriname", code: "SR", flag: "\u{1F1F8}\u{1F1F7}", dialCode: "+597" },
  { name: "Svalbard and Jan Mayen Islands", code: "SJ", flag: "\u{1F1F8}\u{1F1EF}", dialCode: "+47" },
  { name: "Sweden", code: "SE", flag: "\u{1F1F8}\u{1F1EA}", dialCode: "+46" },
  { name: "Switzerland", code: "CH", flag: "\u{1F1E8}\u{1F1ED}", dialCode: "+41" },
  { name: "Syria", code: "SY", flag: "\u{1F1F8}\u{1F1FE}", dialCode: "+963" },
  { name: "Taiwan", code: "TW", flag: "\u{1F1F9}\u{1F1FC}", dialCode: "+886" },
  { name: "Tajikistan", code: "TJ", flag: "\u{1F1F9}\u{1F1EF}", dialCode: "+992" },
  { name: "Tanzania", code: "TZ", flag: "\u{1F1F9}\u{1F1FF}", dialCode: "+255" },
  { name: "Thailand", code: "TH", flag: "\u{1F1F9}\u{1F1ED}", dialCode: "+66" },
  { name: "The Bahamas", code: "BS", flag: "\u{1F1E7}\u{1F1F8}", dialCode: "+1" },
  { name: "Timor-Leste", code: "TL", flag: "\u{1F1F9}\u{1F1F1}", dialCode: "+670" },
  { name: "Togo", code: "TG", flag: "\u{1F1F9}\u{1F1EC}", dialCode: "+228" },
  { name: "Tokelau", code: "TK", flag: "\u{1F1F9}\u{1F1F0}", dialCode: "+690" },
  { name: "Tonga", code: "TO", flag: "\u{1F1F9}\u{1F1F4}", dialCode: "+676" },
  { name: "Trinidad and Tobago", code: "TT", flag: "\u{1F1F9}\u{1F1F9}", dialCode: "+1" },
  { name: "Tunisia", code: "TN", flag: "\u{1F1F9}\u{1F1F3}", dialCode: "+216" },
  { name: "Turkey", code: "TR", flag: "\u{1F1F9}\u{1F1F7}", dialCode: "+90" },
  { name: "Turkmenistan", code: "TM", flag: "\u{1F1F9}\u{1F1F2}", dialCode: "+993" },
  { name: "Turks and Caicos Islands", code: "TC", flag: "\u{1F1F9}\u{1F1E8}", dialCode: "+1" },
  { name: "Tuvalu", code: "TV", flag: "\u{1F1F9}\u{1F1FB}", dialCode: "+688" },
  { name: "Uganda", code: "UG", flag: "\u{1F1FA}\u{1F1EC}", dialCode: "+256" },
  { name: "Ukraine", code: "UA", flag: "\u{1F1FA}\u{1F1E6}", dialCode: "+380" },
  { name: "United Arab Emirates", code: "AE", flag: "\u{1F1E6}\u{1F1EA}", dialCode: "+971" },
  { name: "United Kingdom", code: "GB", flag: "\u{1F1EC}\u{1F1E7}", dialCode: "+44" },
  { name: "United States", code: "US", flag: "\u{1F1FA}\u{1F1F8}", dialCode: "+1" },
  { name: "Uruguay", code: "UY", flag: "\u{1F1FA}\u{1F1FE}", dialCode: "+598" },
  { name: "Uzbekistan", code: "UZ", flag: "\u{1F1FA}\u{1F1FF}", dialCode: "+998" },
  { name: "Vanuatu", code: "VU", flag: "\u{1F1FB}\u{1F1FA}", dialCode: "+678" },
  { name: "Vatican City", code: "VA", flag: "\u{1F1FB}\u{1F1E6}", dialCode: "+379" },
  { name: "Venezuela", code: "VE", flag: "\u{1F1FB}\u{1F1EA}", dialCode: "+58" },
  { name: "Vietnam", code: "VN", flag: "\u{1F1FB}\u{1F1F3}", dialCode: "+84" },
  { name: "Virgin Islands (British)", code: "VG", flag: "\u{1F1FB}\u{1F1EC}", dialCode: "+1" },
  { name: "Virgin Islands (US)", code: "VI", flag: "\u{1F1FB}\u{1F1EE}", dialCode: "+1" },
  { name: "Wallis and Futuna Islands", code: "WF", flag: "\u{1F1FC}\u{1F1EB}", dialCode: "+681" },
  { name: "Western Sahara", code: "EH", flag: "\u{1F1EA}\u{1F1ED}", dialCode: "+212" },
  { name: "Yemen", code: "YE", flag: "\u{1F1FE}\u{1F1EA}", dialCode: "+967" },
  { name: "Zambia", code: "ZM", flag: "\u{1F1FF}\u{1F1F2}", dialCode: "+260" },
  { name: "Zimbabwe", code: "ZW", flag: "\u{1F1FF}\u{1F1FC}", dialCode: "+263" },
];
